version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Logging in to CodeArtifact...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain icl --domain-owner 725740881705 --region ap-south-1 --query authorizationToken --output text)

  build:
    commands:
      - echo Build started on $(date)
      - mvn -v
      - mvn clean install -s settings.xml

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - target/icl-web-project.war
    - appspec.yml
    - scripts/**/*
  # discard-paths removed ← fix